// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3lA_ebRDCZCXlvkNLI3wzokeB740SVcE',
    appId: '1:871121715611:web:d6636386a2f9dd72b3213e',
    messagingSenderId: '871121715611',
    projectId: 'to-do-list-c2ab2',
    authDomain: 'to-do-list-c2ab2.firebaseapp.com',
    storageBucket: 'to-do-list-c2ab2.appspot.com',
    measurementId: 'G-QZTZZ327VF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxPwvNEwVOWOV0ytcXrwvX7uvD5Nkd5b4',
    appId: '1:871121715611:android:20276fb4b4be4293b3213e',
    messagingSenderId: '871121715611',
    projectId: 'to-do-list-c2ab2',
    storageBucket: 'to-do-list-c2ab2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1a_RHPmZGUIrwD4LmzTieFXUpmZnXZjE',
    appId: '1:871121715611:ios:aaf06322803c6ebfb3213e',
    messagingSenderId: '871121715611',
    projectId: 'to-do-list-c2ab2',
    storageBucket: 'to-do-list-c2ab2.appspot.com',
    iosBundleId: 'com.example.baseTodolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1a_RHPmZGUIrwD4LmzTieFXUpmZnXZjE',
    appId: '1:871121715611:ios:297faacfa1d862bdb3213e',
    messagingSenderId: '871121715611',
    projectId: 'to-do-list-c2ab2',
    storageBucket: 'to-do-list-c2ab2.appspot.com',
    iosBundleId: 'com.example.baseTodolist.RunnerTests',
  );
}
